### **Geopandas Practice Sheet**

This notebook serves as a practice of the information learned in our Geopandas modules. This notebook will be preparation for our next Assessment

# 1) Complete the Hierarchy: 
 
 - Shapely Geometry 
       
       ↓
 - GeoSeries
      
       ↓
 - GeoDataFrame

# 2) What type of object is returned by each expression? 

parks.geometry
- Geo Series

parks.geometry.iloc[0]
- Shapely geometry

parks.iloc[0]
- Pandas Series

parks.iloc[[0]]
- Geo Dataframe

In [82]:
import geopandas as gpd

parks = gpd.read_file("../../schedule/week06/GPD_module2/parks.geojson")

In [83]:
type(parks.geometry)

geopandas.geoseries.GeoSeries

In [84]:
type(parks.geometry.iloc[0])

shapely.geometry.polygon.Polygon

In [85]:
type(parks.iloc[0])

pandas.Series

In [86]:
type(parks.iloc[[0]])

geopandas.geodataframe.GeoDataFrame

# 3) Explain in one sentence why `parks.geometry.iloc[0]` does not behave exactly like `parks.geometry`

Adding .iloc[0] to parks.geometry parses the data from the entire GeoSeries to select one individual Shapely geometry, making them different object types and support different behaviors.

# 4. Write code to display all column names in `parks` as a regular Python list.

In [87]:
list(parks.columns)

['FID',
 'AREA_',
 'PERIMETER',
 'PARCELS_',
 'PARCELS_ID',
 'CREATION',
 'SIZE',
 'OWNER',
 'PIN',
 'TMBL',
 'DESC_',
 'DEEDREF',
 'PLAT_BKPG',
 'NAME',
 'TYPE',
 'CATEGORY_1',
 'Acres',
 'GlobalID',
 'Acquired',
 'Year',
 'Shape__Area',
 'Shape__Length',
 'geometry']

# 5. Write code to select only the `NAME` and `geometry` columns from `parks`.

In [88]:
parks[["NAME", "geometry"]]

,NAME,geometry
0,Lewis' Heartleaf Preserve,"POLYGON ((-79.16178 36.22637, -79.16177 36.226..."
1,Cedar Grove Park (additional land),"POLYGON ((-79.13185 36.18019, -79.13185 36.180..."
2,Little River Regional Park,"POLYGON ((-78.96214 36.1786, -78.9615 36.17818..."
3,Little River Regional Park,"POLYGON ((-78.96311 36.16803, -78.96458 36.159..."
4,Lake Orange,"POLYGON ((-79.14132 36.16565, -79.14105 36.165..."
...,...,...
63,Piney Mountain subdivision (Ph1 & 2),"POLYGON ((-79.00298 36.00408, -79.00175 36.004..."
64,,"POLYGON ((-79.10561 35.96395, -79.105 35.96395..."
65,New Hope Preserve,"POLYGON ((-78.99928 35.97958, -78.99935 35.979..."
66,Mountains to Sea Trail access,"POLYGON ((-79.25034 35.95436, -79.2509 35.9536..."
67,Holden Roberts,"POLYGON ((-79.03342 36.10811, -79.03342 36.108..."

# 6. Write code to select the first three rows of `parks` while keeping the result as a GeoDataFrame.

In [89]:
parks.iloc[:3]

,FID,AREA_,PERIMETER,PARCELS_,PARCELS_ID,CREATION,SIZE,OWNER,PIN,TMBL,...,NAME,TYPE,CATEGORY_1,Acres,GlobalID,Acquired,Year,Shape__Area,Shape__Length,geometry
0,1,439075.76317,3466.65190,625,624,09/21/2005,A10.1,ORANGE COUNTY,9950114431,2.5..9G,...,Lewis' Heartleaf Preserve,Parkland & open space,Open space,10.079793,{F8631965-0D35-433C-8905-CDB60CEBD9DF},1.127261e+12,2005,62811.214844,1309.388751,"POLYGON ((-79.16178 36.22637, -79.16177 36.226..."
1,2,522994.28853,3437.57045,2735,2734,02/27/2004,A12.22,ORANGE COUNTY,9868045156,2.34..3,...,Cedar Grove Park (additional land),Parkland & open space,Open space,12.006297,{7BC4B680-934E-4F45-A5A6-848DA677E36B},1.077840e+12,2004,74727.546875,1298.205646,"POLYGON ((-79.13185 36.18019, -79.13185 36.180..."
2,3,290116.18364,4303.44333,2856,2855,11/07/2000,A7.61,ORANGE COUNTY,0818132024,1.21..32,...,Little River Regional Park,Parkland & open space,Existing park,6.660151,{208C409A-D322-4A31-817D-809233335151},9.735552e+11,2000,41450.199219,1629.727739,"POLYGON ((-78.96214 36.1786, -78.9615 36.17818..."

# 7. Write code to inspect the geometry type of every feature in `parks`

In [90]:
parks.geom_type

0     Polygon
1     Polygon
2     Polygon
3     Polygon
4     Polygon
       ...
63    Polygon
64    Polygon
65    Polygon
66    Polygon
67    Polygon
Length: 68, dtype: str

# 8. What does `parks.crs` tell you?

Tells you the coordinate reference system (CRS) the GeoDataFrame is using (how the map coordinates are defined and what units/projection they use)

In [91]:
parks.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

# 9. Why can one point still produce a complete graph when you call `.plot()`?

.plot() creates the entire plotting area (axes, coordinate scale, labels), then draws the singular point as the only spatial feature

In [93]:
one_park = parks.geometry.iloc[0]

# 10. What library provides the geometry object stored in `one_park`?

Shapely library

In [94]:
type(one_park)

shapely.geometry.polygon.Polygon

In [95]:
stops = gpd.read_file("../../schedule/week06/GPD_module2/chapel_hill_bus_stops.geojson")

stops.crs 
# EPSG: 4326

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

# 11. Would EPSG:4326 be a good CRS for measuring distance in feet? Explain briefly.

No. EPSG:4326 uses latitude and longitude measured in degrees, not feet, so it is not appropriate for measuring distance in feet.

# 12. Write code to create `stops_nc` by reprojecting `stops` to EPSG:2264.

In [96]:
stops_nc = stops.to_crs(epsg=2264)

stops_nc.crs

<Projected CRS: EPSG:2264>
Name: NAD83 / North Carolina (ftUS)
Axis Info [cartesian]:
- X[east]: Easting (US survey foot)
- Y[north]: Northing (US survey foot)
Area of Use:
- name: United States (USA) - North Carolina - counties of Alamance; Alexander; Alleghany; Anson; Ashe; Avery; Beaufort; Bertie; Bladen; Brunswick; Buncombe; Burke; Cabarrus; Caldwell; Camden; Carteret; Caswell; Catawba; Chatham; Cherokee; Chowan; Clay; Cleveland; Columbus; Craven; Cumberland; Currituck; Dare; Davidson; Davie; Duplin; Durham; Edgecombe; Forsyth; Franklin; Gaston; Gates; Graham; Granville; Greene; Guilford; Halifax; Harnett; Haywood; Henderson; Hertford; Hoke; Hyde; Iredell; Jackson; Johnston; Jones; Lee; Lenoir; Lincoln; Macon; Madison; Martin; McDowell; Mecklenburg; Mitchell; Montgomery; Moore; Nash; New Hanover; Northampton; Onslow; Orange; Pamlico; Pasquotank; Pender; Perquimans; Person; Pitt; Polk; Randolph; Richmond; Robeson; Rockingham; Rowan; Rutherford; Sampson; Scotland; Stanly; Stokes; Surry; Swain; Transylvania; Tyrrell; Union; Vance; Wake; Warren; Washington; Watauga; Wayne; Wilkes; Wilson; Yadkin; Yancey.
- bounds: (-84.33, 33.83, -75.38, 36.59)
Coordinate Operation:
- name: SPCS83 North Carolina zone (US survey foot)
- method: Lambert Conic Conformal (2SP)
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

# 13. Write code to create an `area_sqft` column in `parks_nc` using polygon geometry area.

In [97]:
parks_nc = parks.to_crs(epsg=2264)

parks_nc["area_sqft"] = parks_nc.geometry.area

# 14. Write code to calculate the distance from every stop in `stops_nc` to a single polygon named `park_1`.

In [98]:
park_1 = parks_nc.geometry.iloc[0]

stops_nc["distance_to_park1"] = stops_nc.geometry.distance(park_1)

# 15.  If `park_1` is a polygon, does `.distance(park_1)` measure distance to the polygon centroid? Explain.

No. It measures the shortest distance from each geometry to the polygon, not to the polygon’s centroid.

# 16. Explain each: 
| Predicate | Meaning |
|---|---|
| within | **Geometry is completely inside another geometry** |
| contains | **Geometry completely contains another geometry** |
| intersects | **Geometries share any space or boundary** |
| touches | **Geometries touch at their boundaries but interiors do not overlap** |

# 17. In `gpd.sjoin(parks, urban, predicate="within")`, which geometry is being tested as within which?

The park geometries are being tested to see whether they are within the urban geometry

In [99]:
urban = gpd.read_file("../../schedule/week06/Geopandas1/data/urban_area.geojson")

gpd.sjoin(parks, urban, predicate="within")

,FID,AREA_,PERIMETER,PARCELS_,PARCELS_ID,CREATION,SIZE,OWNER,PIN,TMBL,...,Shape__Area_left,Shape__Length_left,geometry,index_right,OBJECTID,URBANSER_,URBANSER_I,DATE,Shape__Area_right,Shape__Length_right
26,27,1.678070e+04,542.5457,34005,34004,01/01/1980,L1,ORANGE COUNTY,9799746369,7.52B.I.1,...,2383.140625,204.520447,"POLYGON ((-79.00723 35.93323, -79.00737 35.932...",0,2,2,1,804470400000,7.150418e+08,158917.477493
56,57,2.616359e+06,0.0000,0,0,02/19/2003,60,ORANGE COUNTY,9870855283,,...,371838.156250,2894.699505,"POLYGON ((-79.07569 35.96476, -79.07483 35.964...",0,2,2,1,804470400000,7.150418e+08,158917.477493

# 18. A park crosses an urban-area boundary. Would `within` be True? Would `intersects` be True?

--> Within: False, because the park crosses the urban boundary, so it is not completely inside

--> Intersects: True, because the park and urban area still share some space

# 19. Write code that returns how many stops are inside each polygon in a gpd named `parks` that has three polygons.

In [100]:
parks["stop_count"] = parks.geometry.apply(lambda park: stops.geometry.within(park).sum())

parks[["NAME", "stop_count"]]

                                    NAME  stop_count
0              Lewis' Heartleaf Preserve           0
1     Cedar Grove Park (additional land)           0
2             Little River Regional Park           0
3             Little River Regional Park           0
4                            Lake Orange           0
..                                   ...         ...
63  Piney Mountain subdivision (Ph1 & 2)           0
64                                                 0
65                     New Hope Preserve           0
66         Mountains to Sea Trail access           0
67                        Holden Roberts           0

[68 rows x 2 columns]

In [101]:
urban_parks = gpd.sjoin(parks, urban, predicate="within")

# 20. What is the purpose of `gpd.sjoin()`?

It joins two GeoDataFrames based on a spatial relationship between their geometries, such as within, contains, or intersects.

# 21. Why is a spatial join different from a regular pandas join on a common ID field?

A spatial join matches rows based on where geometries are located relative to each other, while a regular pandas join matches rows using equal values in a shared column or ID.

# 22. Write a spatial join that keeps bus stops that fall inside park polygons. Use `stops` as the left GeoDataFrame and `parks` as the right GeoDataFrame.

In [102]:
stops_in_parks = gpd.sjoin(stops, parks, predicate = "within")

# 23. After a point-in-polygon spatial join, how could you count how many bus stops were matched to each park? Describe the idea or write code

In [103]:
stops_in_parks.groupby("index_right").size()

Series([], dtype: int64)

# 24. Why can a polygon-to-polygon `intersects` spatial join create multiple output rows if each original layer was one polygon in size?

A polygon can intersect multiple polygons in the other GeoDataFrame, so the spatial join creates one output row for each intersecting pair.

# 25. You want to answer: “Which parks are within 500 feet of a bus stop?” Write how would you do this with GeoPandas
**a. using a distance and apply method.**

**b. using buffers**

In [104]:
# Using a Distance & Apply Method

parks_nc["near_stop"] = parks_nc.geometry.apply(lambda park: (stops_nc.geometry.distance(park) <= 500).any())

parks_nc[parks_nc["near_stop"]]

,FID,AREA_,PERIMETER,PARCELS_,PARCELS_ID,CREATION,SIZE,OWNER,PIN,TMBL,...,CATEGORY_1,Acres,GlobalID,Acquired,Year,Shape__Area,Shape__Length,geometry,area_sqft,near_stop
26,27,1.678070e+04,542.54570,34005,34004,01/01/1980,L1,ORANGE COUNTY,9799746369,7.52B.I.1,...,Existing park,0.385232,{AC5ACF2B-C47D-4B35-887F-1742C6F95AEE},2.471904e+11,1977,2383.140625,204.520447,"POLYGON ((1997859.271 794592.568, 1997817.646 ...",1.678071e+04,True
64,65,2.772936e+06,10256.43099,0,0,,,SCHOOL BOARD,,,...,,0.000000,{D7B8F32F-FDEC-45F1-8029-CEDDCBE399AE},NaN,,394099.945312,3866.409721,"POLYGON ((1968746.938 805791.753, 1968927.781 ...",2.772937e+06,True

In [105]:
# Using Buffers

stop_buffers = stops_nc.buffer(500)

parks_nc["near_stop"] = parks_nc.geometry.apply(lambda park: stop_buffers.intersects(park).any())

parks_nc[parks_nc["near_stop"]]

,FID,AREA_,PERIMETER,PARCELS_,PARCELS_ID,CREATION,SIZE,OWNER,PIN,TMBL,...,CATEGORY_1,Acres,GlobalID,Acquired,Year,Shape__Area,Shape__Length,geometry,area_sqft,near_stop
26,27,1.678070e+04,542.54570,34005,34004,01/01/1980,L1,ORANGE COUNTY,9799746369,7.52B.I.1,...,Existing park,0.385232,{AC5ACF2B-C47D-4B35-887F-1742C6F95AEE},2.471904e+11,1977,2383.140625,204.520447,"POLYGON ((1997859.271 794592.568, 1997817.646 ...",1.678071e+04,True
64,65,2.772936e+06,10256.43099,0,0,,,SCHOOL BOARD,,,...,,0.000000,{D7B8F32F-FDEC-45F1-8029-CEDDCBE399AE},NaN,,394099.945312,3866.409721,"POLYGON ((1968746.938 805791.753, 1968927.781 ...",2.772937e+06,True