## NumPy Homework Juniper Notebook

In this notebook, we are practicing our python indexing, pandas indexing, and new NumPy skills in preparation for our next in class assessment

**Python Indexing**

In [39]:
locations = ["Oak", "Pine", "Maple", "Cedar", "Elm"]

In [40]:
# What is returned by locations[0]?
locations[0]

'Oak'

In [41]:
# locations[4]?
locations[4]

'Elm'

In [42]:
# locations[1:4]?
locations[1:4]

['Pine', 'Maple', 'Cedar']

In [43]:
# Index expression that returns "Maple"
locations[2]

'Maple'

In [44]:
points = [[100,200], [140,230], [180,260], [120,280]]

In [45]:
# points[2]?
points[2]

[180, 260]

In [46]:
# points[2][1]? Explain what each index selects
 # - [2] selects the 2nd index which is [180,260] and [1] selects the 1st index of that which is 260
points[2][1]

260

In [47]:
# Expression that returns the x-coordinate of the second point - All coords stored as [x,y]
points[1][0]

140

**Pandas Indexing**

In [48]:
import pandas as pd

df = pd.DataFrame({"name": ["Oak", "Pine", "Maple", "Cedar"], "ft": [25, 48, 31, 60], "zone": ["A", "B", "A", "B"]})

In [81]:
# Type of Object returned by df["ft"]
 # - Series [[]] would be a dataframe
type(df["ft"])

pandas.Series

In [50]:
# Code to select the name & ft columns together
df[["name", "ft"]]

    name  ft
0    Oak  25
1   Pine  48
2  Maple  31
3  Cedar  60

In [51]:
# Row returned by df.iloc[1]?
 # - Row 2 
df.iloc[1]

name    Pine
ft        48
zone       B
Name: 1, dtype: object

In [52]:
# Code using iloc to select 1st 3 rows
df.iloc[0:3]

    name  ft zone
0    Oak  25    A
1   Pine  48    B
2  Maple  31    A

In [53]:
# Code to select rows where ft is > 30 
df["ft"] > 30

0    False
1     True
2     True
3     True
Name: ft, dtype: bool

In [54]:
# Rows returned by df.iloc[1:3]?
 # - Rows 2 & 3
df.iloc[1:3]

    name  ft zone
1   Pine  48    B
2  Maple  31    A

**NumPy Arrays**

In [55]:
import numpy as np 

points = np.array([[100,200], [140,230], [180,260], [120,280]])

In [56]:
## What does points.shape return? what do the 2 numbers mean?
 # - 4 is # of rows, 2 is # of columns - 4 pts w/ 2 coordinates each 

points.shape

(4, 2)

In [57]:
# points[0]?
points[0]

array([100, 200])

In [58]:
# points[0,1]?
points[0,1]

np.int64(200)

In [59]:
# points[:, 0]? Explain colon
 # - Colon selects all rows, 0 selects the first column
points[:, 0]

array([100, 140, 180, 120])

In [60]:
 # points[:, 1]?
points[:, 1]

array([200, 230, 260, 280])

In [61]:
# Code that returns second and third rows
points[1:3]

array([[140, 230],
       [180, 260]])

In [62]:
# Compare points[2][1] w/ points[2,1]
 # - Both return same value... ones a list of lists and other is an array
points[2][1] == points[2,1]

np.True_

**Vectorized Operations**

In [63]:
shift = np.array([10,20])

In [64]:
# Determine result of points + shift
 # - Before coding I think : array([[110, 220], [150, 250], [190, 280], [130, 300]])
points + shift

array([[110, 220],
       [150, 250],
       [190, 280],
       [130, 300]])

In [65]:
# Why does this operation not require a Python for loop?
 # - Numpy can apply to operation across the whole array @ once, b/c it understands array shapes & broadcasts across every row

**Boolean Masks & Spatial Queries**

In [66]:
x = points[:, 0]
y = points[:, 1]

inside = (x >= 110) & (x <= 150) & (y >= 220) & (y <= 290)

In [69]:
# Write the boolean values stored inside [:]
 # - [False, True, False, True]
inside[:]

array([False,  True, False,  True])

In [68]:
# points[inside]? 
 # - array([[140,230], [120, 280]])
points[inside]

array([[140, 230],
       [120, 280]])

In [ ]:
# In GIS language, what spatial operation is this Boolean mask approximating?
 # - It is approximating points that fall w/in a rectangular bounding (box) area

**np.where() & Classification**

In [70]:
elevation = np.array([240, 510, 430, 680])
classes = np.where(elevation >= 500, 1, 0)

In [71]:
# What values are stored in classes[:]?
 # - [0, 1, 0, 1]
classes[:]

array([0, 1, 0, 1])

In [72]:
# Explain the 3 arguments in np.where(condition, value_if_true, value_if_false)
 # - condition is the test being applied to the array; value_if_true is the value assigned to the array if true; value_if_false is the value assigned to the array if false

**Distance and Pandas Connection**

In [74]:
a = np.array([100, 200])
b = np.array([140, 230])
distance = np.sqrt(((a-b) ** 2)).sum()

In [ ]:
# What does a - b return?
 # - [-40, -30] ; [(xa - xb), (ya - yb)] 
a - b

array([-40, -30])

In [77]:
# Explain why distance calculation is an example of vectorized arithemetic
# - It is vectorized arithemetic because Numpy performs the subtraction and squaring on both coordinate values @ once w/out using a for loop

In [78]:
ft_array = df["ft"].to_numpy()

In [80]:
# What type of object is ft_array?
 # - It will be a NumPy array since it was converted from a pandas series to NumPy
type(ft_array)

numpy.ndarray

In [82]:
# What happened to pandas index & column label when the Series was converted to NumPy?
 # - The index & column labels were removed, only the data values remain in the array

**Big Picture**

| Structure | Expression | What it selects |
|---|---|---|
| Python list | `locations[2]` | **The 3rd item in the list** |
| Nested Python list | `points_list[2][1]` | **The 2nd item from the 3rd inner list** |
| pandas DataFrame | `df.iloc[2, 1]` | **The value in the 3rd row and 2nd column** |
| NumPy array | `points[2, 1]` | **The value in the 3rd row and 2nd column (y-coord of 3rd point)** |
| NumPy array | `points[:, 0]` | **All rows from the 1st column (All x-coords)** |

In [84]:
# Main Indexing Idea that's same across Python, pandas, & Numpy?
 # - Indexing starts at 0, so position 0 is the first item, position 1 is the second, etc.

In [83]:
# What becomes easier when data are arranged as a 2-D NumPy array?
 # - Selecting coordinates, filtering points, and doing vectorized math without loops.